import { createStyles, getStylesRef, MantineTheme } from '@mantine/core';

export const useStyles = createStyles(({ white }: MantineTheme) => ({
  card: {
    ref: getStylesRef('card'),
    padding: '0 0 1rem 0 !important',
    display: 'flex',
    width: '20.03125rem',
    'padding-bottom': '0px',
    'flex-direction': 'column',
    'align-items': 'center',
    gap: '1rem',
    'flex-shrink': 0,
    'border-radius': '0.75rem',
    border: '1.126px solid var(--Black-100, #ECECEE)',
    background: white,
  },
  section: {
    ref: getStylesRef('section'),
    '&[data-last]': {
      marginBottom: 0,
      borderBottom: 0,
    },
  },
  imageSection: {
    ref: getStylesRef('imageSection'),
    padding: '0',
    overflow: 'hidden',
    pointerEvents: 'none',
    userSelect: 'none',
    '& img': {
      objectFit: 'cover',
      height: '13.65256rem',
    },
    width: '19.91588rem',
    height: '13.65256rem',
  },
  infoAndActionSection: {
    display: 'flex',
    width: '17.6875rem',
    'flex-direction': 'column',
    'align-items': 'flex-start',
    gap: '1.4075rem',
  },
  infoSection: {
    display: 'flex',
    'flex-direction': 'column',
    'align-items': 'flex-start',
    gap: '0.8445rem',
    'align-self': 'stretch',
    width: '100%',
    padding: 0,
    margin: 0,
  },
  name: {
    color: 'var(--mantine-color-dark-6, #201F22)',
    'font-size': '1.25rem',
    'font-style': 'normal',
    'font-weight': '700',
    'line-height': 'normal',
  },
  priceSection: {
    display: 'flex',
    'justify-content': 'space-between',
    'align-items': 'center',
    'align-self': 'stretch',
  },
  priceTitle: {
    color: 'var(--mantine-color-dark-1, #A3A3A3)',
    'font-size': '0.875rem',
    'font-style': 'normal',
    'font-weight': '500',
    'line-height': 'normal',
    padding: 0,
    margin: 0,
  },
  price: {
    color: 'var(--mantine-color-dark-6, #201F22)',
    'font-size': '1.25rem',
    'font-style': 'normal',
    'font-weight': '700',
    'line-height': 'normal',
    padding: 0,
    margin: 0,
  },
  buttonSection: {
    width: '100%',
    padding: 0,
    margin: 0,
  },
  button: {
    display: 'flex',
    flex: '1 0 0',
  },
}));
