import { createStyles, MantineTheme } from '@mantine/core';

export const useStyles = createStyles((theme: MantineTheme) => ({
  root: {
    display: 'flex',
    width: '19.6875rem',
    padding: '1.25rem',
    // gap: '0.625rem',
    'border-radius': '0.75rem',
    border: '1px solid var(--mantine-color-gray-3, #ECECEE)',
    background: theme.white,
    'flex-direction': 'column',
    'align-items': 'flex-start',
    gap: '2rem',
    flex: '1 0 0',
  },
  title: {
    color: 'var(--mantine-color-dark-6, #201F22)',
    'font-size': '1.25rem',
    'font-style': 'normal',
    'font-weight': '700',
    'line-height': 'normal',
    margin: 0,
    padding: 0,
  },
  separatingLine: {
    height: '0rem',
    'align-self': 'stretch',
    'stroke-width': '1px',
    stroke: 'var(--mantine-color-dark-2, #CFCFCF)',
    borderBottom: '1px solid var(--mantine-color-gray-4, #CFCFCF)',
    width: '100%',
  },
  priceSection: {
    display: 'flex',
    'justify-content': 'space-between',
    'align-items': 'center',
    'align-self': 'stretch',
    margin: 0,
    padding: 0,
  },
  priceTitle: {
    display: 'flex',
    width: '9rem',
    'flex-direction': 'column',
    'justify-content': 'center',
    'align-self': 'stretch',
    color: 'var(--mantine-dark-4, #767676)',
    'font-size': '1rem',
    'font-style': 'normal',
    'font-weight': '400',
    'line-height': '1.25rem',
    margin: 0,
    padding: 0,
  },
  priceValue: {
    color: 'var(--mantine-color-dark-6, #201F22)',
    'text-align': 'right',
    'font-size': '1rem',
    'font-style': 'normal',
    'font-weight': '700',
    'line-height': '1.25rem',
    margin: 0,
    padding: 0,
  },
  form: {
    width: '100%',
  },
  button: {
    width: '100%',
  },
}));
